export const Users = [
    {
      id: 1,
      name: "Taneesha Mirwani",
      username: "taneesho",
      email: "tanishoo.m@gmail.com",
      profilePicture: "/assets/person/person1.jpg",
    },
    {
      id: 2,
      name: "Taniya Tiwari",
      username: "taniya.13",
      email: "tiwari.tiwari@gmail.com",
      profilePicture: "/assets/person/person2.jpg",
    },
    {
      id: 3,
      name: "Stuti Roy",
      username: "stutiii_6",
      email: "stutiiii@gmail.com",
      profilePicture: "/assets/person/person3.jpg",
    },
    {
      id: 4,
      name: "Yash Bhatia",
      username: "yash.bhatiaa",
      email: "bhatia@gmail.com",
      profilePicture: "/assets/person/person4.jpg",
    },
    
  ];
  export const Usersonline = [
    {
      id: 1,
      name: "Sanket Metha",
      username: "sankett25",
      email: "sanket@gmail.com",
      profilePicture: "/assets/person/friend1.jpg",
    },
    {
      id: 2,
      name: "Aashna Hegde",
      username: "aashnahegde",
      email: "aashna1@gmail.com",
      profilePicture: "/assets/person/friend2.jpg",
    },
    {
      id: 3,
      name: "Rishabh Chawla",
      username: "rishabhchawlaaa",
      email: "rish12@gmail.com",
      profilePicture: "/assets/person/friend3.jpg",
    },
    {
      id: 4,
      name: "Aditya Kumar",
      username: "addykumar",
      email: "addy.k@gmail.com",
      profilePicture: "/assets/person/friend4.jpg",
    },
    {
      id: 5,
      name: "Ashima Khanna",
      username: "ashi_khanna",
      email: "khanna14@gmail.com",
      profilePicture: "/assets/person/friend5.jpg",
    },
    {
      id: 6,
      name: "Unnati Malharkar",
      username: "unnati_m",
      email: "malharkar1unnati@gmail.como",
      profilePicture: "/assets/person/friend6.jpg",
    },
    {
      id: 7,
      name: "Manav Chabbra",
      username: "mr.mnv",
      email: "mnvofficial@gmail.com",
      profilePicture: "/assets/person/friend7.jpg",
    },
    {
      id: 8,
      name: "Nischal Sinha",
      username: "Nish_12",
      email: "nish.s@gmail.com",
      profilePicture: "/assets/person/friend8.jpg",
    },
    {
      id: 9,
      name: "Mrunal Panchal",
      username: "mrunuu",
      email: "mrunal@gmail.com",
      profilePicture: "/assets/person/friend9.jpg",
    },
    {
      id: 10,
      name: "Anirudh Sharma",
      username: "ani_s",
      email: "sharma.work@gmail.com",
      profilePicture: "/assets/person/friend10.jpg",
    },
    {
      id: 11,
      name: "Kritika Khurana",
      username: "thatbohogirl",
      email: "bohogirl@karina.biz",
      profilePicture: "/assets/person/friend11.jpg",
    },
  ];
  
  export const Posts = [
    {
      userId: 3,
      id: 1,
      title: "to make a blinded choice to reject or provident to task",
      body: "I know why they’re called shades, because you can’t see me roll my eyes when I wear them.",
      photo: "/assets/posts/post1.jpg",
      date: "5 mins ago",
      like: "100",
      comment: "70",
    },
    {
      userId: 2,
      id: 2,
      title: "who is to be",
      body: "Butterflies I like dream creatures in reality.",
      photo: "/assets/posts/post2.jpg",
      date: "23 mins ago",
      like: "480",
      comment: "112",
    },
    {
      userId: 1,
      id: 3,
      title: "abuse her as an exercise in who she or she is",
      body: "Make sure everyone in your boat is rowing, and not drilling holes when you’re not looking.",
      photo: "/assets/posts/post3.jpg",
      date: "10 hours ago",
      like: "10",
      comment: "30",
    },
  
    {
      userId: 3,
      id: 4,
      title: "he is blinded",
      body: "Embrace the waves.Stay salty.",
      photo: "/assets/posts/post4.jpg",
      date: "23 hours ago",
      like: "10",
      comment: "30",
    },
    {
      userId: 4,
      id: 5,
      title: "know how to hate",
      body: "Until you step into the unknown, you don’t know what you’re made of.",
      photo: "/assets/posts/post5.jpg",
      date: "2 days ago",
      like: "560",
      comment: "200",
    },
    {
      userId: 2,
      id: 6,
      title: "I will open them for my great sorrow",
      body: "Reality called, so I hung up and went kayaking, Just add water.",
      photo: "/assets/posts/post6.jpg",
      date: "2 days ago",
      like: "130",
      comment: "31",
    },
    {
      userId: 1,
      id: 7,
      title: "great but easy",
      body: "The best thing about playing with dolls is that you can pretend to be anyone you want to be.",
      photo: "/assets/posts/post7.jpg",
      date: "2 weeks ago",
      like: "10",
      comment: "30",
    },
    {
      userId: 4,
      id: 8,
      title: "pain is the actual pain",
      body: "",
      photo: "/assets/posts/post8.jpg",
      date: "3 weeks ago",
      like: "780",
      comment: "412",
    },
    {
      userId: 1,
      id: 9,
      title: "know the right time and the pain of all the accusers",
      body: "",
      photo: "/assets/posts/post9.jpg",
      date: "2 months ago",
      like: "10",
      comment: "3",
    },
    {
      userId: 2,
      id: 10,
      title: "choice that's annoying for him",
      body: "",
      photo: "/assets/posts/post10.jpg",
      date: "4 months ago",
      like: "86",
      comment: "12",
    },
    {
      userId: 3,
      id: 11,
      title: "and it is true for those who praise it",
      body: "",
      photo: "/assets/posts/post11.jpg",
      date: "1 year ago",
      like: "1000",
      comment: "340",
    },
    {
      userId: 1,
      id: 12,
      title: "at some time hate is pain",
      body: "",
      photo: "/assets/posts/post12.jpg",
      date: "1 year ago",
      like: "760",
      comment: "500",
    },
    {
      userId: 2,
      id: 13,
      title: "pain as a tenderness and often pleasure in the mind",
      body: "",
      photo: "/assets/posts/post13.jpg",
      date: "10 hours ago",
      like: "10",
      comment: "30",
    },
    {
      userId: 4,
      id: 14,
      title: "pleasure of choosing option",
      body: "",
      photo: "/assets/posts/post14.jpg",
      date: "1 year ago",
      like: "48",
      comment: "7",
    },
  ];